Repository Ryuzeans/Nojeans.ver2, pull requests merged in 2023-05, with the labels that each got.

#14 [Radin feat/#1] - Create Font Extension
  MC2.xcodeproj/project.pbxproj
  MC2/Extension/FontExtension.swift
Labels: feat

#22 [Design] MainView Design Complete
  MC2.xcodeproj/project.pbxproj
  MC2/Resource/Assets.xcassets/Main/Contents.json
  MC2/Resource/Assets.xcassets/Main/Image1.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Main/Image1.imageset/Image1.png
  MC2/Resource/Assets.xcassets/Main/Image2.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Main/Image2.imageset/Image2.png
  MC2/Resource/Assets.xcassets/Main/Image3.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Main/Image3.imageset/Image3.png
  MC2/View/DoubleView/DoubleTapView4.swift
  MC2/View/MainView/CustomButton.swift
  MC2/View/MainView/MainView.swift
Labels: design

#25 [Feat] TapView
  MC2.xcodeproj/project.pbxproj
  MC2/Resource/Assets.xcassets/Tap/Bell.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Tap/Bell.imageset/Group 33.png
  MC2/Resource/Assets.xcassets/Tap/Contents.json
  MC2/Resource/Assets.xcassets/Tap/RButton.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Tap/RButton.imageset/R) Button_re.png
  MC2/Resource/Assets.xcassets/Tap/TouchBall.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Tap/TouchBall.imageset/R)_TouchBall.png
  MC2/View/TapView/TapView.swift
  MC2/View/TapView/TapView1.swift
  MC2/View/TapView/TapView2.swift
  MC2/View/TapView/TapViewMain.swift
Labels: feat

#28 [Chore] Intergration GestureView
  MC2.xcodeproj/project.pbxproj
  MC2/MC2App.swift
  MC2/Resource/Assets.xcassets/Color/HeaderColor.colorset/Contents.json
  MC2/Resource/Assets.xcassets/Double/Contents.json
  MC2/Resource/Assets.xcassets/Double/paste_bar.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Double/paste_bar.imageset/paste_bar.png
  MC2/Resource/Assets.xcassets/Double/sample.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Double/sample.imageset/sample.jpeg
  MC2/Resource/Assets.xcassets/Double/search_bar.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Double/search_bar.imageset/search_bar.png
  MC2/Resource/Assets.xcassets/sample.imageset/517BEDCE-D3A0-4607-B18A-ECAADAEE1FFA_1_105_c.jpeg
  MC2/View/DoubleView/DoubleTapView.swift
  MC2/View/DoubleView/DoubleTapView1.swift
  MC2/View/DoubleView/DoubleTapView2.swift
  MC2/View/DoubleView/DoubleTapView4.swift
  MC2/View/DragView/DragViewMain.swift
  MC2/View/LongPressView/LongPressMainView.swift
  MC2/View/MainView/CustomButton.swift
  MC2/View/MainView/MainView.swift
  MC2/View/PanView/PanViewMain.swift
  MC2/View/PanView/SwipeView/SwipeViewMain.swift
  MC2/View/RotationView/RotationViewMain.swift
  MC2/View/TapView/TapViewMain.swift
  MC2/View/ZoomView/ZoomViewMain.swift
Labels: chore

#31 [Design/#26] mod swipe & long press
  MC2.xcodeproj/project.pbxproj
  MC2/Resource/Assets.xcassets/Tap/TouchBall.imageset/Contents.json
  MC2/View/LongPressView/LongPressMainView.swift
  MC2/View/LongPressView/LongPressView1.swift
  MC2/View/LongPressView/LongPressView2.swift
  MC2/View/SwipeView/SwipeView1.swift
  MC2/View/SwipeView/SwipeView2.swift
  MC2/View/SwipeView/SwipeView3.swift
  MC2/View/SwipeView/SwipeViewMain.swift
Labels: design

#32 Bulmang design/#29
  MC2/View/DoubleView/DoubleTapView1.swift
  MC2/View/DoubleView/DoubleTapView2-1.swift
  MC2/View/DoubleView/DoubleTapView2.swift
  MC2/View/DoubleView/DoubleTapView3.swift
  MC2/View/DoubleView/DoubleTapView4.swift
  MC2/View/MainView/MainView.swift
Labels: design

#39 [Radin_Design/#33] mod swipe view & long view
  MC2/Extension/FontExtension.swift
  MC2/Resource/Assets.xcassets/swipe.imageset/Contents.json
  MC2/Resource/Assets.xcassets/swipe.imageset/swipe.svg
  MC2/View/LongPressView/LongPressMainView.swift
  MC2/View/LongPressView/LongPressView1.swift
  MC2/View/LongPressView/LongPressView2.swift
  MC2/View/SwipeView/SwipeView1.swift
  MC2/View/SwipeView/SwipeView2.swift
  MC2/View/SwipeView/SwipeView3.swift
  MC2/View/SwipeView/SwipeViewMain.swift
Labels: design

#47 Wesley feat/#16
  MC2/Resource/Assets.xcassets/Tap/TouchBell2.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Tap/TouchBell2.imageset/TouchBell2.png
  MC2/Resource/Assets.xcassets/Tap/bell2.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Tap/bell2.imageset/bell2.png
  MC2/View/TapView/TapView.swift
  MC2/View/TapView/TapView1.swift
  MC2/View/TapView/TapView2.swift
Labels: design

#54 [Design/#51] modified rotation view
  MC2.xcodeproj/project.pbxproj
  MC2/View/RotationView/RotationView2.swift
  MC2/View/RotationView/RotationView2Map.swift
  MC2/View/RotationView/RotationViewMain.swift
  MC2/View/SwipeView/SwipeView1.swift
Labels: design, feat

#59 [Design] add temporary logo icon
  MC2/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MC2/Resource/Assets.xcassets/AppIcon.appiconset/llogo.png
  MC2/Resource/Assets.xcassets/AppIcon.appiconset/logoball.png
Labels: design

#68 [Design] modify button size at all final view and add text to swipe &…
  MC2/Extension/FontExtension.swift
  MC2/Extension/ViewExtension.swift
  MC2/Resource/Assets.xcassets/Longpress/Contents.json
  MC2/Resource/Assets.xcassets/Longpress/long.imageset/Contents.json
  MC2/Resource/Assets.xcassets/Longpress/long.imageset/long.png
  MC2/View/DoubleView/DoubleTapViewFinal.swift
  MC2/View/DragView/DragViewFinal.swift
  MC2/View/LongPressView/LongPressFinalView.swift
  MC2/View/LongPressView/LongPressMainView.swift
  MC2/View/LongPressView/LongPressView1.swift
  MC2/View/LongPressView/LongPressView2.swift
  MC2/View/PanView/PanViewFinal.swift
  MC2/View/RotationView/RotationViewFinal.swift
  MC2/View/SwipeView/SwipeView3.swift
  MC2/View/SwipeView/SwipeViewFinal.swift
  MC2/View/ZoomView/ZoomViewFinal.swift
Labels: design
